stages:
  data_preparation:
    cmd: python src/stage_1_prepdata.py
    deps:
    - src/stage_1_prepdata.py
    - src/utils
    - data/data.xml
    outs:
    - artifacts/prepared

  featurization:
    cmd: python src/stage_2_featurization.py
    deps:
    - src/stage_2_featurization.py
    - src/utils
    - artifacts/prepared
    outs:
    - artifacts/features